apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traccar-timescaledb-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: traccar-timescaledb-secrets
  data:
    - secretKey: pg-username
      remoteRef:
        key: apps/traccar
        property: postgres_user
    - secretKey: pg-password
      remoteRef:
        key: apps/traccar
        property: postgres_password
