apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: scanservjs
  namespace: apps
spec:
  parentRefs:
    - name: cilium-gateway-https
      namespace: kube-system
      sectionName: web-gw
  hostnames:
    - "scanner.mcmumf.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: scanservjs
          port: 3000
