apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiobookshelf-secrets
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: media-secret-store
    kind: ClusterSecretStore
  target:
    name: audiobookshelf-secrets
  data:
    - secretKey: secret_key
      remoteRef:
        key: media/audiobookshelf
        property: jwt-secret-key
