apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch-secrets
  namespace: linkwarden
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: meilisearch-secrets
  data:
    - secretKey: master-key
      remoteRef:
        key: apps/linkwarden
        property: meili-master-key
