apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkwarden

resources:
  - external-secrets.yaml

helmCharts:
  - name: meilisearch
    repo: https://meilisearch.github.io/meilisearch-kubernetes
    releaseName: meilisearch
    namespace: linkwarden
    version: 0.25.1
    valuesFile: values.yaml
