apiVersion: v1
kind: Service
metadata:
  name: meilisearch-svc
  namespace: linkwarden
  labels:
    app: meilisearch-app
spec:
  ports:
    - port: 7700
      name: web
  selector:
    app: meilisearch-app
