apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infra-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
  data:
    - secretKey: client_id
      remoteRef:
        key: infra/prom-stack
        property: oidc-client-id

    - secretKey: client_secret
      remoteRef:
        key: infra/prom-stack
        property: oidc-client-secret
