apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./openebs

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prom-stack
    namespace: monitoring
    version: 81.4.3
    valuesFile: values.yaml
    includeCRDs: true
