apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-secrets
  namespace: linkwarden
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: linkwarden-secrets
  data:
    - secretKey: nextauth-secret
      remoteRef:
        key: apps/linkwarden
        property: nextauth-secret
    - secretKey: client-id
      remoteRef:
        key: apps/linkwarden
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: apps/linkwarden
        property: client-secret
