apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: linkwarden-gateway
  namespace: linkwarden
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    app: linkwarden-app
spec:
  gatewayClassName: cilium
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: links.mcmumf.dev
      name: http
      port: 80
      protocol: HTTP
