apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkwarden-http-route
  namespace: linkwarden
  labels:
    app.kubernetes.io/instance: linkwarden
    app.kubernetes.io/name: linkwarden
spec:
  parentRefs:
    - name: linkwarden-gateway
  hostnames:
    - "links.mcmumf.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: linkwarden-svc
          port: 3000
