apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkwarden-http-route
  namespace: traccar
  annotations:
    gethomepage.dev/description: Collect, read, annotate, and fully preserve what matters, all in one place
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Homelab
    gethomepage.dev/icon: https://raw.githubusercontent.com/linkwarden/linkwarden/refs/heads/main/assets/logo.png
    gethomepage.dev/name: Linkwarden
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=linkwarden"
  labels:
    app: linkwarden-app
spec:
  parentRefs:
    - name: linkwarden-gateway
  hostnames:
    - "links.mcmumf.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: linkwarden-svc
          port: 3000
