apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkwarden

resources:
  - db/
  - meilisearch/
  - external-secrets.yaml
  - gateway.yaml
  - http-route.yaml
  - service.yaml
  - statefulset.yaml
