apiVersion: v1
kind: Service
metadata:
  name: linkwarden-svc
  namespace: linkwarden
  labels:
    app: linkwarden-app
spec:
  ports:
    - port: 3000
      name: web
  selector:
    app: linkwarden-app
