apiVersion: v1
kind: Service
metadata:
  name: linkwarden-svc
  namespace: linkwarden
  labels:
    app: linkwarden-app
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: linkwarden-app
