apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellystat-secrets
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: media-secret-store
    kind: ClusterSecretStore
  target:
    name: jellystat-secrets
  data:
    - secretKey: jwt
      remoteRef:
        key: media/jellystat
        property: jwt-secret
