apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: freshrss-backup
spec:
  schedule: "0 0 2 * * *" # At 0200 every day
  method: volumeSnapshot
  backupOwnerReference: cluster
  cluster:
    name: freshrss-cnpg
