apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-server-secrets
  namespace: actualbudget
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: actual-budget-secrets
  data:
    - secretKey: client-id
      remoteRef:
        key: apps/actual-budget
        property: oauth-client-id
    - secretKey: client-secret
      remoteRef:
        key: apps/actual-budget
        property: oauth-client-secret
