apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-server-secrets
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: actual-server-secrets
    kind: ClusterSecretStore
  target:
    name: jellystat-secrets
  data:
    - secretKey: jwt
      remoteRef:
        key: apps/actual-server
        property: jwt-secret
