apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actual-server
  namespace: actualbudget
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - actual.mcmumf.dev
      secretName: actual.mcmumf.dev-tls
  rules:
    - host: actual.mcmumf.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: actual-server
                port:
                  number: 5006
