apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actual-server
  namespace: actualbudget
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    gethomepage.dev/description: Budgeting
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Homelab
    gethomepage.dev/icon: https://raw.githubusercontent.com/actualbudget/actual/refs/heads/master/packages/docs/static/img/favicon.webp
    gethomepage.dev/name: Actual Budget
    gethomepage.dev/pod-selector: "app=actual-server"
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - actual.mcmumf.dev
      secretName: actual.mcmumf.dev-tls
  rules:
    - host: actual.mcmumf.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: actual-server
                port:
                  number: 5006
