apiVersion: v1
kind: Service
metadata:
  name: actual-server
  namespace: actual-server
  labels:
    app: actual-server
spec:
  selector:
    app: actual-server
  ports:
    - port: 5006
      name: actual-server
