apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wger
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/McMumf/homelab"
      targetRevision: "main"
      path: kubernetes/applications/wger
  destination:
    server: https://kubernetes.default.svc
    namespace: wger
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
