apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wger

helmCharts:
  - name: github-wger
    repo: https://wger-project.github.io/helm-charts
    releaseName: wger
    namespace: wger
    version: 0.2.4
    valuesFile: values.yaml
