app:
  timezone: "America/New_York"
  global:
    image:
      tag: 2.4
  persistence:
    enabled: true
    storageClass: "openebs"
    accessModes: ["ReadWriteOnce"]
  axes:
    enabled: true
    failureLimit: 10
    # in minutes
    cooloffTime: 30
    # number of reverse proxies involved
    ipwareProxyCount: 1
    # order of magnitude from last proxy for the real ip
    ipwareMetaPrecedenceOrder: "X_FORWARDED_FOR,REMOTE_ADDR"
  environment:
    - name: SITE_URL
      value: "https://fitness.mcmumf.dev"

celery:
  enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  url: fitness.mcmumf.dev
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    gethomepage.dev/description: Fitness Tracker
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Homelab
    gethomepage.dev/icon: https://raw.githubusercontent.com/wger-project/wger/master/wger/core/static/images/logos/logo.png
    gethomepage.dev/name: wger
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=wger-app"
