apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  protocol: "nvmf"
  repl: "3"
  allowVolumeExpansion: "true"
  encrypted: "true"
allowVolumeExpansion: true
reclaimPolicy: Retain
provisioner: io.openebs.csi-mayastor
