# a single replica thin provisioned storage class intended for backups
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-backup
parameters:
  protocol: "nvmf"
  repl: "1"
  allowVolumeExpansion: "true"
  thin: "true"
  encrypted: "true"
  poolAffinityTopologyLabel: |
    purpose: snapshot-storage
allowVolumeExpansion: true
provisioner: io.openebs.csi-mayastor
