apiVersion: v1
kind: Service
metadata:
  name: freshrss-svc
  namespace: media
  labels:
    app: freshrss-app
spec:
  ports:
    - port: 80
      name: freshrss-web
  selector:
    app: freshrss-app
