apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traccar
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/McMumf/homelab"
      targetRevision: "main"
      path: kubernetes/applications/traccar
  destination:
    server: https://kubernetes.default.svc
    namespace: traccar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
