apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-app-test
  namespace: traccar
spec:
  parentRefs:
    - name: traccar-gateway
  hostnames:
    - "loc.mcmumf.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: traccar
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /osmand
      backendRefs:
        - name: external-traccar
          port: 5055
