apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traccar-ingress
  namespace: traccar
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - loc.mcmumf.dev
      secretName: loc.mcmumf.dev-tls
  rules:
    - host: loc.mcmumf.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traccar
                port:
                  number: 80
    - host: loc.mcmumf.dev
      http:
        paths:
          - path: /osmand
            pathType: Prefix
            backend:
              service:
                name: external-traccar
                port:
                  number: 5055
