apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traccar

resources:
  - ./db
  - gateway.yaml
  - http-route.yaml

helmCharts:
  - name: traccar
    repo: https://traccar.github.io/traccar-helm/
    releaseName: traccar
    namespace: traccar
    version: 1.9.0
    valuesFile: values.yaml
