apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkwarden

resources:
  - scheduled-backup.yaml

helmCharts:
  - name: cluster
    repo: https://cloudnative-pg.github.io/charts
    releaseName: linkwarden-cnpg
    namespace: linkwarden
    version: 0.5.0
    valuesFile: values.yaml
