apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: network-secret-store
spec:
  provider:
    vault:
      # Reach vault from inside the cluster.
      server: http://vault.vault.svc.cluster.local:8200
      path: network
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets
