apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs

resources:
  - ./diskpools
  - namespace.yaml
  - ./storage-classes

# helmCharts:
#   - name: openebs
#     repo: https://openebs.github.io/openebs
#     releaseName: openebs
#     namespace: openebs
#     version: 4.4.0
#     includeCRDs: true
#     valuesFile: values.yaml
