apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: jellystat-backup
spec:
  schedule: "0 0 6 * * *" # At 0200 every day
  method: volumeSnapshot
  backupOwnerReference: cluster
  cluster:
    name: jellystat-cnpg
