apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-secrets
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infra-secret-store
    kind: ClusterSecretStore
  target:
    name: pocket-id-secrets
  data:
    - secretKey: smtp-host
      remoteRef:
        key: infra/pocket-id
        property: email_host
    - secretKey: smtp-user
      remoteRef:
        key: infra/pocket-id
        property: email_user
    - secretKey: smtp-password
      remoteRef:
        key: infra/pocket-id
        property: email_password
    - secretKey: encryption-key
      remoteRef:
        key: infra/pocket-id
        property: encryption-key
