apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocket-id

resources:
  - db/
  - external-secrets.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml
  - statefulset.yaml
