apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  serviceName: "pocket-id"
  replicas: 1
  selector:
    matchLabels:
      app: pocket-id
  template:
    metadata:
      labels:
        app: pocket-id
    spec:
      automountServiceAccountToken: false
      containers:
        - name: pocket-id
          image: ghcr.io/pocket-id/pocket-id:v2
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
              ephemeral-storage: 4Gi
            limits:
              cpu: 100m
              memory: 1Gi
              ephemeral-storage: 4Gi
          env:
            - name: APP_URL
              value: "https://pocket-id.mcmumf.dev"
            - name: TRUST_PROXY
              value: "true"
          ports:
            - name: pocket-id
              containerPort: 1411
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /app/pocket-id
                - healthcheck
            initialDelaySeconds: 10
            periodSeconds: 90
            failureThreshold: 2
            timeoutSeconds: 5
          volumeMounts:
            - name: pocket-id-data
              mountPath: /app/data
  volumeClaimTemplates:
    - metadata:
        name: pocket-id-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "openebs"
        resources:
          requests:
            storage: 4Gi
