apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hortusfox-secrets
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: hortusfox-secrets
  data:
    - secretKey: admin-email
      remoteRef:
        key: apps/hortusfox
        property: admin-email

    - secretKey: admin-password
      remoteRef:
        key: apps/hortusfox
        property: admin-password

    - secretKey: mariadb-password
      remoteRef:
        key: apps/hortusfox
        property: mariadb-password

    - secretKey: mariadb-root-password
      remoteRef:
        key: apps/hortusfox
        property: mariadb-root-password

    - secretKey: smtp-username
      remoteRef:
        key: apps/hortusfox
        property: smtp-user

    - secretKey: smtp-password
      remoteRef:
        key: apps/hortusfox
        property: smtp-token

    - secretKey: smtp-host
      remoteRef:
        key: apps/hortusfox
        property: smtp-server
