apiVersion: v1
kind: Service
metadata:
  name: hortusfox-svc
  namespace: apps
  labels:
    app: hortusfox
spec:
  ports:
    - port: 8080
      name: hortusfox-port
      targetPort: 80
      protocol: TCP
  clusterIP: None
  selector:
    app: hortusfox
