apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-secrets
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: mealie-secrets
  data:
    - secretKey: client-id
      remoteRef:
        key: apps/mealie
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: apps/mealie
        property: client-secret
