# Note: Example file, please don't actually use this...make your own
apiVersion: v1
kind: Secret
metadata:
  name: pool-encr-secret
  namespace: mayastor
type: Opaque
immutable: true
stringData:
  encryption_parameters: |
    {
      "cipher": "AesXts",
      "key": "2b7e151628aed2a6abf7158809cf4f3c",
      "key_len": 128,
      "key2": "2b7e151628aed2a6abf7158809cf4f3d",
      "key2_len": 128
    }
