apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: skylab
  namespace: openebs
spec:
  node: skylab
  disks: ["uring:///dev/disk/by-id/wwn-0x500a07511ad725d0"]
  encryptionConfig:
    source:
      secret:
        name: pool-encr-secret
