apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infra-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: infra/authentik
        property: secret_key

    - secretKey: email-host
      remoteRef:
        key: infra/authentik
        property: email_host

    - secretKey: email-username
      remoteRef:
        key: infra/authentik
        property: email_user

    - secretKey: email-password
      remoteRef:
        key: infra/authentik
        property: email_password
