apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

helmCharts:
  - name: cluster
    repo: https://cloudnative-pg.github.io/charts
    releaseName: authentik-cnpg
    namespace: authentik
    version: 0.5.0
    valuesFile: values.yaml
