apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-backup
spec:
  schedule: "0 0 4 * * *" # At 0200 every day
  method: volumeSnapshot
  backupOwnerReference: cluster
  cluster:
    name: authentik-cnpg
