apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: outline

helmCharts:
  - name: cluster
    repo: https://cloudnative-pg.github.io/charts
    releaseName: outline-cnpg
    namespace: outline
    version: 0.4.0
    valuesFile: values.yaml
